- id: '1671887023006'
  alias: Github_Push
  description: ''
  trigger:
  - platform: time
    at: '16:10:00'
  condition: []
  action:
  - service: shell_command.pushupdates_to_github
    data: {}
  mode: single
