- id: '1671887023006'
  alias: Github_Push
  description: ''
  trigger:
  - platform: time
    at: '16:10:00'
  condition: []
  action:
  - service: shell_command.pushupdates_to_github
    data: {}
  mode: single
- id: '1673428338655'
  alias: sms сообщения на айфон
  description: ''
  trigger:
  - platform: time
    at: '16:00:00'
  condition: []
  action:
  - service: notify.mobile_app_iphone_misac_igor
    data:
      message: “Your Roommate arrived”
      data:
        push:
          sound: 3rdParty_Success_Haptic.caf
          badge: 0
          service: notify.telegram_id_1
          data:
            message: privet
  mode: single
- id: '1673596839724'
  alias: Новая автоматизация
  description: ''
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    context:
      user_id:
      - d8b1fe73edc542409fed32eaa4532482
    event_data:
      action: ALARM
  condition: []
  action:
  - service: notify.mobile_app_iphone_misac_igor
    data:
      message: HA message ALARM
      data:
        actions:
        - action: URL
          title: Notification Histori
          url: settings://notification_history
  mode: single
