- id: '1671887023006'
  alias: Github_Push
  description: ''
  trigger:
  - platform: time
    at: '16:10:00'
  condition: []
  action:
  - service: shell_command.pushupdates_to_github
    data: {}
  mode: single
- id: '1673428338655'
  alias: sms сообщения на айфон
  description: ''
  trigger:
  - platform: time
    at: '16:00:00'
  condition: []
  action:
  - service: notify.mobile_app_iphone_misac_igor
    data:
      message: “Your Roommate arrived”
      data:
        push:
          sound: 3rdParty_Success_Haptic.caf
          badge: 0
  mode: single
- id: '1673596839724'
  alias: Новая автоматизация
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_button.lr_light_cinema
  condition: []
  action:
  - service: notify.mobile_app_iphone_misac_igor
    data:
      message: HA message ALARM
      data:
        actions:
        - action: URL
          url: www.yotube.com
    enabled: true
  mode: single
- id: '1674196687260'
  alias: Git_Buckup_Button
  description: 'При нажатие на кнопку '
  trigger:
  - platform: state
    entity_id:
    - input_button.github_puch
  condition: []
  action:
  - service: shell_command.pushupdates_to_github
    data: {}
  mode: single
