homeassistant:
  name: My Smart Home
  packages: !include_dir_merge_named includes/packages


# Loads default set of integrations. Do not remove.
default_config:

lovelace:
  mode: yaml
input_button:


# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
binary_sensor: !include_dir_merge_list includes/bin_sensor

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'

telegram_bot:
  - platform: polling
    api_key: !secret api_key_bot
    allowed_chat_ids:
      - !secret telegram_id_1
      
notify:

  - name: telegram_id_1
    platform: telegram
    chat_id: !secret telegram_id_1
    
shell_command:
    pushupdates_to_github: /bin/bash pushupdates.sh

